"""Generate a Python source fixture that constructs a Pydantic model
equivalent to a parsed LEF/DEF/etc. file.

Pipeline:

    file ──parse──► dict ──Pydantic.model_validate──► typed model
                                                          │
                                              ┌──── pyfixture.to_python
                                              ▼
                                      Python source

The output is a runnable Python module:

    from <models_module> import *

    obj = LEF(libraries=[Library(...), ...])

    if __name__ == "__main__":
        ...  # save back through rawast

When executed, the module reconstructs the same in-memory model.
`model_dump(exclude_none=True, by_alias=True)` on the result yields
a dict structurally equal to the original parsed dict, and
`g.save(...)` on that dict yields the original file (modulo
grammar-canonical formatting).

Use cases:
  * Test fixtures — convert a real corpus file into self-contained
    Python that builds the same AST.
  * Tutorials / examples — readable typed code mirroring a real LEF.
  * Programmatic editing — start from a real file, edit in Python
    with IDE autocomplete + Pydantic validation, save back.

Limitations:
  * Output size grows linearly with input. Multi-MB files produce
    multi-MB Python source. Practical for files <~5MB; impractical
    for production-scale outputs.
  * Repetitive content (e.g. 1000 similar macros) emits 1000 separate
    constructor calls — no loop / comprehension synthesis.
"""

from __future__ import annotations

from typing import Any
import textwrap


def to_python(
    model: Any,
    *,
    models_module: str,
    grammar_path: str | None = None,
    source_path: str | None = None,
    start: str | None = None,
) -> str:
    """Render a Pydantic model instance as Python source.

    The output module imports `*` from `models_module` and binds a
    single `obj` to a constructor expression that reconstructs the
    model. If `grammar_path` is given, the module also includes a
    `__main__` block that loads the grammar, dumps `obj` to a dict,
    and prints the saved bytes — so running the file regenerates
    the original input.
    """
    header_parts = [
        '"""Generated by `rawast pycode`.',
        "",
    ]
    if source_path:
        header_parts.append(f"Source file: {source_path}")
    if grammar_path:
        header_parts.append(f"Grammar:     {grammar_path}")
    if start:
        header_parts.append(f"Start rule:  {start}")
    header_parts.append('"""')
    header_parts.append("")
    header_parts.append(f"from {models_module} import *  # noqa: F401, F403")
    header_parts.append("")
    header = "\n".join(header_parts)

    body = "obj = " + _render(model, indent=0)

    if grammar_path:
        main_block = textwrap.dedent(f'''
            if __name__ == "__main__":
                import sys
                import rawast

                g = rawast.Grammar.load({grammar_path!r})
                dumped = obj.model_dump(exclude_none=True, by_alias=True)
                sys.stdout.buffer.write(g.save(dumped, start={start!r}))
        ''').strip()
        return header + "\n" + body + "\n\n\n" + main_block + "\n"
    return header + "\n" + body + "\n"


# --- Internals ---------------------------------------------------------------

# Indent step for pretty-printing nested constructor calls.
_STEP = "    "

# Above this many fields/items, a constructor or list breaks across lines.
# Below it, the value stays on one line for compactness.
_INLINE_THRESHOLD = 1


def _render(obj: Any, *, indent: int) -> str:
    """Render any Pydantic value as Python source."""
    # Pydantic v2 import is local to avoid a hard dep on pydantic for
    # users who only need the parser; the function is only reached
    # from CLI paths that already require pydantic.
    from pydantic import BaseModel

    if isinstance(obj, BaseModel):
        return _render_model(obj, indent=indent)
    if isinstance(obj, list):
        return _render_list(obj, indent=indent)
    if isinstance(obj, dict):
        return _render_dict(obj, indent=indent)
    if obj is None or isinstance(obj, (bool, int, float, str)):
        return repr(obj)
    # Fall back to repr for any unhandled type.
    return repr(obj)


def _render_model(obj: Any, *, indent: int) -> str:
    """Render a Pydantic BaseModel as `ClassName(field=value, ...)`."""
    cls_name = type(obj).__name__
    # Collect non-None fields. Skip None to keep the output compact;
    # the round-trip through model_dump(exclude_none=True) means None
    # fields don't affect the saved bytes anyway. We use the Python
    # FIELD NAME for the kwarg, not the alias — aliases may be Python
    # keywords (e.g. `class` for LEF's CLASS field) which can't appear
    # as kwargs. Pydantic resolves field-name kwargs at construction
    # time; the alias is only used on the dict/JSON side via
    # `populate_by_name=True` (set by the Pydantic generator).
    fields = []
    for name in type(obj).model_fields:
        value = getattr(obj, name)
        if value is None:
            continue
        fields.append((name, value))

    if not fields:
        return f"{cls_name}()"

    # Decide inline vs multi-line based on field count and value
    # complexity. A model with a single primitive field stays inline;
    # anything with a nested model or list breaks across lines.
    rendered = [(name, _render(value, indent=indent + 1)) for name, value in fields]
    is_complex = (
        len(fields) > _INLINE_THRESHOLD
        or any("\n" in r for _, r in rendered)
    )

    if not is_complex:
        # Inline: ClassName(field=value)
        parts = ", ".join(f"{n}={v}" for n, v in rendered)
        return f"{cls_name}({parts})"

    # Multi-line: each field on its own line, indented.
    pad_inner = _STEP * (indent + 1)
    pad_outer = _STEP * indent
    lines = [f"{cls_name}("]
    for n, v in rendered:
        lines.append(f"{pad_inner}{n}={v},")
    lines.append(f"{pad_outer})")
    return "\n".join(lines)


def _render_list(items: list[Any], *, indent: int) -> str:
    if not items:
        return "[]"

    rendered = [_render(item, indent=indent + 1) for item in items]
    is_complex = (
        len(items) > _INLINE_THRESHOLD
        or any("\n" in r for r in rendered)
    )

    if not is_complex:
        return "[" + ", ".join(rendered) + "]"

    pad_inner = _STEP * (indent + 1)
    pad_outer = _STEP * indent
    lines = ["["]
    for r in rendered:
        lines.append(f"{pad_inner}{r},")
    lines.append(f"{pad_outer}]")
    return "\n".join(lines)


def _render_dict(d: dict[Any, Any], *, indent: int) -> str:
    """Bare dict (rare — most everything ends up as a Pydantic model,
    but the grammar may produce an open-schema dict for a sub-tree
    that didn't get a typed class).
    """
    if not d:
        return "{}"
    rendered = [
        (_render(k, indent=indent + 1), _render(v, indent=indent + 1))
        for k, v in d.items()
    ]
    is_complex = (
        len(d) > _INLINE_THRESHOLD
        or any("\n" in r for _, r in rendered)
    )
    if not is_complex:
        parts = ", ".join(f"{k}: {v}" for k, v in rendered)
        return "{" + parts + "}"
    pad_inner = _STEP * (indent + 1)
    pad_outer = _STEP * indent
    lines = ["{"]
    for k, v in rendered:
        lines.append(f"{pad_inner}{k}: {v},")
    lines.append(f"{pad_outer}}}")
    return "\n".join(lines)
